# pytorch_lightning==2.0.9
seed_everything: 42
trainer:
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      log_model: true
      project: lti_ica
      save_dir:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 32-true
  callbacks: null
  fast_dev_run: false
  max_epochs: 3000
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 10
  num_sanity_val_steps: null
  log_every_n_steps: 20
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: 0.5
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
model:
  triangular: false
  zero_means: true
  lr: 0.001
  model: mlp
  offline: true
data:
  num_comp: 2
  num_data_per_segment: 12000
  num_segment: 3
  dt: 0.003
  triangular: false
  use_B: true
  zero_means: true
  max_variability: false
  use_C: true
  system_type: lti
  ar_order: 1
  batch_size: 64
notes: null
tags: null
ckpt_path: null
