# pytorch_lightning==2.0.9
seed_everything: 42
trainer:
  max_epochs: 100
  gradient_clip_val: 0.5
  gradient_clip_algorithm: norm
  log_every_n_steps: 50
model:
  triangular: false
  zero_means: true
  lr: 1e-2
  model: mlp
  control_dim: 1
data:
  system_type: dc_motor
  batch_size: 8
  dt: 1e-2
  max_variability: false
  num_data_per_segment: 5000
notes: null
tags: null
ckpt_path: null
